import Head from "next/head";

const Header = () => (
    <Head>
        <title>Guitar store</title>
        <meta name="description" content="Generated by create next app for Guitar store"/>
        <link rel="icon" href="/favicon.ico"/>
    </Head>
);

export default Header;
